version: '3'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - main_network
    volumes:
      - wordpress:/var/www/html/wordpress

  maria:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - main_network
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress_container
    build: ./requirements/wordpress
    image: wordpress
    restart: on-failure
    ports:
      - 9000:9000
    networks:
      - main_network
    env_file:
      - .env
    depends_on:
      - maria
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  main_network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ahakam/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ahakam/data/wordpress 
      o: bind
