version: '3'
services:
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - main_network
    volumes:
      - wordpress:/var/www/html/wordpress

  maria:
    build: ./requirements/maria
    container_name: maria
    restart: on-failure
    ports:
      - 3306:3306
    networks:
      - main_network
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    build: ./requirements/express
    container_name: wordpress_container
    restart: always
    ports:
      - 9000:9000
    networks:
      - main_network
    env_file:
      - .env
    depends_on:
      - maria
    volumes:
      - wordpress:/var/www/html/wordpress

networks:
  main_network:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /Users/ahakam/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /Users/ahakam/data/wordpress 
      o: bind
